name: iql

agent_name: ${now:%Y%m%d}_sac_gnn  # Agent name for training or evaluation (default: today's date + '_sac_gnn')

cplexpath: "/opt/opl/bin/x86-64_linux/"  # Defines directory of the CPLEX installation
  
directory: "saved_files"  # Defines directory where to save files

max_episodes: 10000  # Number of episodes to train agent (default: 16k)

no_cuda: true  # Disables CUDA training

batch_size: 100  # Defines batch size

p_lr: 1e-3  # Define policy learning rate

q_lr: 1e-3  # Defines q-value learning rate

hidden_size: 256  # Defines hidden units in the MLP layers

clip: 500  # Clip value for gradient clipping (default: 500)

checkpoint_path: "IQL"  # Path where to save model checkpoints
  
rew_scale: 0.01  # Defines reward scale

input_size: 13 # Number of node features

test_episodes: 10 # Number of episodes to test agent

quantile: 0.7 #quantile value for quantile regression

temperature: 1.0 #temperature value for advantage weighted regression

data_path: "dataset" # Path to the data directory

samples_buffer: 60000 # Number of samples in the replay buffer

clip_score: 100 